# Generated by Django 5.1.7 on 2025-03-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Blog Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
            ],
        ),
    ]
