# Generated by Django 5.1.7 on 2025-03-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Django', 'Django'), ('Machine Learning', 'Machine Learning'), ('React', 'React'), ('Computer Vision', 'Computer Vision'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('MLOps', 'MLOps'), ('Business', 'Business'), ('Others', 'Others'), ('Project', 'Project')], default='Project', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Cover Image'),
        ),
    ]
